=encoding utf8

=head1 NAME

Acme::Honkidasu - 本気出すコピペ

=head1 SYNOPSIS

  use 5.010;
  use Time::Piece;
  use Acme::Honkidasu;
  binmode STDOUT, 'utf8';

  my $now = localtime;
  say $now->honkidasu;
  say $now->strftime('%F %!');

=head1 DESCRIPTION

Acme::Honkidasu is 来月から本気を出す。

=head1 METHOD

=head2 honkidasu

  use Time::Piece;

  say localtime->honkidasu;

  # or

  my $now = localtime;
  say Acme::Honkidasu::honkidasu($now);

来月から本気だす。

=head1 EXTEND strftime

  say localtime->strftime('%F %!');

add conversion specifier character '%!' to 来月から本気を出す。

=head1 AUTHOR

hayajo E<lt>hayajo@cpan.orgE<gt>

=head1 LICENSE

This library is free software; you can redistribute it and/or modify
it under the same terms as Perl itself.


=cut

